DROP TABLE CUSTOMER CASCADE;
DROP TABLE PHONE_NUMBER CASCADE;

CREATE TABLE CUSTOMER (
    CUSTOMER_ID SERIAL PRIMARY KEY,
    NAME TEXT
);

CREATE TABLE PHONE_NUMBER(
    ID SERIAL PRIMARY KEY,
    CUSTOMER_ID INT,
    NUMBER TEXT,
    TYPE TEXT,
    FOREIGN KEY (CUSTOMER_ID)
    REFERENCES CUSTOMER(CUSTOMER_ID)
);